---

aws_credentials: ENCRYPTED[4ca070bffe28eb9b27d63c568b52970dd46f119c3a83b8e443241e895dbf1737580b4d84eed27a311a2b74287ef9f79f]

# Confirm building the remote client, natively on a Mac OS-X VM.
osx_alt_build_task:
    name: "OSX Cross"
    alias: osx_alt_build
    ec2_instance:
        image: amzn-ec2-macos-*
        type: ${EC2_INST_TYPE}
        region: us-east-1
        architecture: amd64
    env:
        EC2_INST_TYPE: "mac1.metal"
        DISTRO_NV: macos-ventura
        CTR_FQIN: notused
        TEST_FLAVOR: "altbuild"
        ALT_NAME: 'OSX Cross'
    setup_script:
        - brew install go
        - brew install go-md2man
        - go version
    build_amd64_script:
        - make podman-remote-release-darwin_amd64.zip
    build_arm64_script:
        - make podman-remote-release-darwin_arm64.zip
    build_pkginstaller_script:
        - cd contrib/pkginstaller
        - make ARCH=amd64 NO_CODESIGN=1 pkginstaller
        - make ARCH=aarch64 NO_CODESIGN=1 pkginstaller
