---

# Default timeout for each task
timeout_in: 60m

aws_credentials: ENCRYPTED[4ca070bffe28eb9b27d63c568b52970dd46f119c3a83b8e443241e895dbf1737580b4d84eed27a311a2b74287ef9f79f]

m1_mac_test_task:
    # https://cirrus-ci.org/guide/persistent-workers/
    persistent_worker:
      labels:
        arch: arm64
    # FIXME: Basic e2e fails after 90s timeout; https://github.com/containers/podman/issues/20535
    allow_failures: $CI == $CI
    env:
      CIRRUS_SHELL: "/bin/bash"  # sh is the default
      # go complains if this is under /tmp or /private/tmp/ (cirrus default)
      CIRRUS_WORKING_DIR: "$HOME/ci/task-${CIRRUS_TASK_ID}"
      # Prevent cache-pollution fron one task to the next
      GOPATH: "$CIRRUS_WORKING_DIR/.go"
      GOCACHE: "$CIRRUS_WORKING_DIR/.go/cache"
      GOENV: "$CIRRUS_WORKING_DIR/.go/support"
      # Consumed by podman-machine ginkgo tests
      CONTAINERS_MACHINE_PROVIDER: "applehv"
      # TODO: Should not require a special image, for now it does.
      MACHINE_IMAGE: "https://fedorapeople.org/groups/podman/testing/applehv/arm64/fedora-coreos-38.20230925.dev.0-applehv.aarch64.raw.gz"
      # TODO: Should be in makefile
      GINKGO_TAGS: "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp remote"
    # TODO: This is a shared instance, if the previous task to use the host was
    # canceled/aborted/timedout, it would leave $HOME in a dirty state, possibly
    # even with unwanted processes still running.
    prep_script: &mac_cleanup
        - set +e  # ignore any failures
        - killall podman vfkit gvproxy
        - rm -rf /private/tmp/ci/* /private/tmp/ci/.??*
        - find ${ORIGINAL_HOME:-$HOME}/ci -mindepth 1 -maxdepth 1 -not -name "*task-${CIRRUS_TASK_ID}*" -prune -exec rm -rf '{}' +
        - true  # Always exit cleanly
    # Requires pre-installed: go go-md2man coreutils vfkit from brew
    setup_script:
      - echo "PATH=$CIRRUS_WORKING_DIR/bin/darwin:$PATH" >> $CIRRUS_ENV
      # Simplify cleanup by confining $HOME and $TMPDIR
      - echo "ORIGINAL_HOME=$HOME" >> $CIRRUS_ENV
      - echo "HOME=$HOME/ci" >> $CIRRUS_ENV
      - echo "TMPDIR=/private/tmp/ci" >> $CIRRUS_ENV
      - source $CIRRUS_ENV
      - mkdir -p $TMPDIR
    envars_script:
      - printenv
    build_script:
      - pwd
      - go version
      - go env
      - make .install.ginkgo
      - make podman-remote
      - make podman-mac-helper
    smoke_script:
      - vfkit --version
      - timeout --preserve-status --foreground --kill-after 1m 10m ./bin/darwin/podman --log-level=debug machine init --image-path $MACHINE_IMAGE
      - timeout --preserve-status --foreground --kill-after 1m 10m ./bin/darwin/podman --log-level=debug machine start
      - timeout --preserve-status --foreground --kill-after 10s 2m ./bin/darwin/podman run -i --rm quay.io/libpod/alpine:latest echo HelloWorld
      # FIXME: https://github.com/containers/podman/issues/20516
      -  ./bin/darwin/podman --log-level=debug machine rm --force || true
    post_smoke_cleanup_script: *mac_cleanup
    e2e_script:
      # TODO: Can this please be a make target?
      - DEBUG_MACHINE=1 ./test/tools/build/ginkgo -vv --tags "$GINKGO_TAGS" -timeout=90m --trace --no-color --focus-file "basic_test.go" pkg/machine/e2e/.
    always:
      # Try not to leave any leaked processes or useless temp files lying around forever.
      task_cleanup_script: *mac_cleanup
